version: 2
updates:
  # NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Action
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
