name: "Build Backend"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.cs'
      - '**.csproj'
      - '.github/workflows/build-backend.yml'
  push:
    paths:
      - '**.cs'
      - '**.csproj'
      - '.github/workflows/build-backend.yml'

env:
  DOTNET_VERSION: '9.0'

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        submodules: recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore