name: "Publish"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  DOTNET_VERSION: '9.0'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache .NET Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.fsproj', '**/*.vbproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install Dependencies
        run: dotnet restore

      - name: Build and Publish
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          echo "Building version $VERSION"
          dotnet publish Imprex.Queries.csproj -c Release -o app -r linux-x64 --self-contained true /p:UseAppHost=true /p:Version=$VERSION

      - name: Run Tests
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          echo "Running tests for version $VERSION"
          dotnet test --configuration Release --no-build

      - name: Pack Project
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          echo "Packing version $VERSION"
          dotnet pack Imprex.Queries.csproj --configuration Release --no-build /p:PackageVersion=$VERSION

      - name: Push NuGet Package
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          echo "Pushing NuGet package for version $VERSION"
          dotnet nuget push Imprex.Queries.${VERSION}.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
